### ISSUE TITLE
PgUp, PgDn, + specific keyboard

### ISSUE THREAD

**Issue by yschaeff** [acro5piano/wayremap#2]
Yank from reddit:

> Ooh nice. I have a usecase. Could you tell me if that would be supported?
> 
> On my laptop keyboard PageUp and PageDown are smooshed to the arrow keys, and I keep hitting them by mistake. I would like to disable them in the terminal (mostly happens using a shell or vim).
> 
> Perhaps remap them to [Win]+[PageDown] in case I need them anyway. BUT I do not want to disable them on my external keyboard (or alternatively when an external keyboard is connected.)

So I would line to disable some keys on a specific input device and enable keys with modifiers (shift, win, etc)

**Comment by acro5piano** [comment]
Hi, thanks for your interest!

> I would like to disable them in the terminal (mostly happens using a shell or vim).

You want to remap `PgUp` and `PgDn` to nothing only in terminal, right?

If so, that should be implemented by the following code:

```python
from wayremap.config import WayremapConfig, Binding
from wayremap.main import run
import uinput as k

wayremap_config = WayremapConfig(
    applications=[
        'Alacritty',
        'kitty',
        # TODO: put your terminal app_id(wayland) or window_class(x) here
    ],
    bindings=[
        # TODO: implement these keycode by editing this, meaning the library update needed!
        # https://github.com/acro5piano/wayremap/blob/79e782c00add9b77cc445f2b6471a0fd11cc83b5/wayremap/keycode_map.py#L3
        Binding('ctrl.alt.PageUp', [[]]),
        Binding('ctrl.alt.PageDown', [[]]),
    ])

# TODO: put your keyboard input id by path
run(wayremap_config, '/dev/input/event4')
```

(Note that such keys are not implemented yet)

> I do not want to disable them on my external keyboard

This is easy as `wayremap` just intercept key input on a specific input device.

**Comment by acro5piano** [comment]
I think it should be possible to implement it:

![image](https://user-images.githubusercontent.com/10719495/145680446-babc8392-cb87-46c9-9eff-dfc94017de6e.png)

(how to get all possible values? I'm not familiar with Python much)

**Comment by acro5piano** [comment]
I must work on this:

https://github.com/acro5piano/wayremap/issues/3

**Comment by yschaeff** [comment]
Well for me it is mostly annoying in the terminal. Disabling it everywhere is also fine. 

Admittedly I only skimmed over your code. So brush aside the following advice in case my understanding is incorrect. I see you use your own (input) mapping syntax ('ctr.alt.a') and therefore you are now asking yourself how to list all possible values so you can have your mapping file up to date.

`Binding('ctrl.alt.a', [[k.KEY_LEFTCTRL, k.KEY_HOME]]),`

But consider the following syntax:

`Binding([k.CTRL, k.ALT, k.A], [[k.KEY_LEFTCTRL, k.KEY_HOME]]),`

Now for every binding you only need to check if they are all pressed, but no need to map. I think this will simplify your code by a lot.

btw `evdev.ecodes.KEY.values()` might give you all keys as strings if you need to.

**Comment by acro5piano** [comment]
Thanks for your suggestion, it is very helpful!

> But consider the following syntax:

This is a good solution. At first I was creating a clone of `xremap` and I thought the current one is the proper syntax, but your suggestion is more straightforward way.

> btw evdev.ecodes.KEY.values() might give you all keys as strings if you need to.

Thanks! I didn't notice it.

I'll create a new version implicating  your suggestion soon! If you send a PR for that I'll merge it.

Thanks

**Comment by acro5piano** [comment]
@yschaeff
I've supported all keys on https://github.com/acro5piano/wayremap/issues/2 - can you take a look to see if this is what you are looking for? Thanks!
